(function() {
    var config = require.config({
        baseUrl: 'js',
        paths: {
            samples: '../samples/compiled',
            templates: '../templates',
            test_screenplays: '../test/data/test_screenplays',
            jquery: '../node_modules/jquery/dist/jquery',
            handlebars: '../node_modules/handlebars/dist/handlebars',
            logger: 'libs/logger',
            saveAs: '../node_modules/file-saver/FileSaver',
            d3: '../node_modules/d3/d3',
            modernizr: 'libs/modernizr',
            pdfkit: 'libs/pdfkit',
            impromptu: 'libs/jquery-impromptu.min',
            jstree: '../node_modules/jstree/dist/jstree',
            cookie: 'libs/jquery.cookie',
            dropbox: 'libs/dropbox.min',
            protoplast: '../node_modules/protoplast/dist/protoplast',
            acceptance: '../test/acceptance',
            off: '../node_modules/off/off',
            text: '../node_modules/text/text',
            Blob: 'libs/Blob'
        },
        shim: {
            handlebars: {
                exports: 'Handlebars'
            },
            logger: {
                exports: 'Logger'
            },
            saveAs: {
                exports: 'saveAs'
            },
            modernizr: {
                exports: 'Modernizr'
            },
            dropbox: {
                exports: 'Dropbox'
            },
            Blob: {
                exports: 'Blob'
            }
        }
    });

    // __TEST and __COVERAGE global vars are generated by template task
    // when creating runner.html and coverage.html test runners
    if (typeof __TEST !== 'undefined') {
        config.baseUrl = '../js/';
        require.config(config);
    }
    else if (typeof __COVERAGE !== 'undefined') {
        config.baseUrl = '../coverage/js/';
        require.config(config);
    }
})();