/**
		
	Do not edit this file. It's generated automatically from template/acceptance.tests.template.
		
*/
define(['../acceptance/spec/editor', '../acceptance/spec/open', '../acceptance/spec/smoke'], function() {});