/**
		
	Do not edit this file. It's generated automatically from template/acceptance.tests.template.
		
*/
define(['../acceptance/spec/app', '../acceptance/spec/editor', '../acceptance/spec/monitor', '../acceptance/spec/open', '../acceptance/spec/settings', '../acceptance/spec/smoke'], function() {});